let dico = {
"notext":"translation(翻訳)",
"aasye": "to ascend (昇る)",
"abelu": "to begin to unwrap (ほころぶ)",
"acary": "apocalypse (黙示)",
"adda": "to bully (抉れる)",
"advelses": "loop-de-loop (宙返り)",
"albel": "to rest (休む)",
"aldaltia": "to strangle (絞める)",
"alter": "monster/demon (魔物)",
"aihel": "to exist (いる/ある)",
"ail": "full (満/全て)",
"ailes": "to resemble (似ている)",
"ail Scape": "everywhere (どこへだって)",
"ailjfa": "to be satisfied (満たす)",
"aishellm": "distress (無我夢中)",
"aisia": "feeling (感覚)",
"ait": "to cut (切る)",
"ajarla": "to bear (抱える)",
"aka": "water (水)",
"akaite": "fluid (～液)",
"ald": "to put (つける)",
"alger": "crowd (雑踏)",
"alista": "create (創る)",
"alice": "Alice",
"allss": "eyelid (目蓋)",
"alvete": "welcome (ようこそ)",
"amb": "strong (強い)",
"entilk": "strong (強い)",
"amadimel": "lost person/child (迷子)",
"ame": "child (子)",
"amejdimer": "fetus (胎児)",
"amie": "love (愛)",
"amil": "wake up (目を覚める)",
"amiy": "to love (愛する)",
"amnist": "yesterday (昨日)",
"andauraspray": "cacophony (不協和音)",
"ani": "a (一 (counter))",
"anie": "breath (息)",
"piino": "breath (息)",
"antakt": "to dive (潜る)",
"anyahel": "combine to one place (全てはひとつになって)",
"aola": "now (今)",
"apeilf yullk": "floating (揺蕩う)",
"apka": "rope (ロープ)",
"apnesia": "visit (訪れる) / Certainly (確かに)",
"aprout": "guarantee (保障)",
"arche": "top (上)",
"arch": "top (上)",
"arel": "streak (勿怪)",
"ardand": "skill (技)",
"ariqlowt": "reason/Theory (理) (romanized as “kotowari”)",
"arla": "white (白い)",
"arlistielim": "all things (万象)",
"ark": "celestial (天)",
"arriziam": "to head towards (向かう)",
"arsa": "ash (灰)",
"arth": "to remain",
"arupe": "ancient (古代)",
"ary": "to go through (抜ける)",
"asta": "electricity (電気)",
"atherty": "evolution (進化)",
"awdrom": "order/Command (命令)",
"awlsijvikt": "plotted out (筋書き通り)",
"awlst": "ready (準備する)",
"awter": "to meet (会う/逢う)",
"bai": "already/Not anymore (もう)",
"baly": "always (いつだって)",
"bekti": "be afraid (怖がる)",
"bektit": "afraid (怖がる)",
"bell": "remember (覚える)",
"belqua": "to get packed, to get crowded (込む)",
"belzebav": "beelzebub (ベルゼブブ)",
"berte": "mountain (山)",
"biibell": "irregular (不揃い)",
"bip": "insect (虫)",
"bipqls": "insects",
"bipeid": "to Wriggle (蠢く)",
"bipeidit": "wriggling (蠢く)",
"blawpelee": "popcorn (ポップコーン)",
"bllink": "blink (明滅する)",
"blu": "wherever (何処[...]も)",
"brai": "inside (中)",
"brait": "open/Breath (開ける/息吹)",
"tordu": "open/Breath (開ける/息吹)",
"briss": "grow apart (すれ違う)",
"brou": "cloud (雲)",
"brous": "storm (嵐)",
"canvie": "once more (もう一度) / Change (変わる)",
"capite": "capital (帝都)",
"caren": "silence (静寂)",
"cat": "cat (猫)",
"cate": "walk (歩く)/ Glorify (謳歌する)",
"ceeka": "bar (格子)",
"cees": "ice wall (氷壁) / Pale Blue (水色)　/ Frozen (凍る)",
"chail": "key (鍵)",
"challen": "echo (響く)",
"chronicle": "chronicle (年代記)",
"circus": "circus",
"clooshe": "close (閉める)",
"clooshela": "closet (クローゼット)",
"cloud": "you (あなた)",
"cloudyte": "you (あなた)",
"cliid": "fall (from sky) (降りる/注ぐ)",
"cobbs": "fly (蠅)",
"colista": "seek (求める) / to beg (乞う)",
"coll": "body (体)",
"colt": "cold (冷たい)",
"compass": "compass",
"crai": "you (君)",
"crait": "your (君の)",
"craill": "crai+ll(?)",
"crute": "intersection (交差点)",
"dangli": "to get soaked (漬ける)",
"darlitte": "curtain (of show) (幕)",
"deank": "thanks (感謝/ありがとう)",
"deet": "reach (届く)",
"dex": "right (右)",
"di": "two (二)",
"diallif": "die (死ぬ/息絶える)",
"dialoss": "wither (枯れる)",
"diazz": "twins",
"dibytt": "to be clouded with (覆う)",
"digris": "to obtain (手にする)",
"diiza": "beside (そば)",
"dijap": "déjà vu (デジャヴ)",
"dijsya": "to prevent (阻む)",
"dikteb": "to construct (構築する)",
"dikti": "unfortunate (不幸)",
"dikzim": "to be intoxicated (酔い痴れる)",
"arsia": "reason/Purpose (理由/所以/ため)",
"arsiam": "might relate to arsia",
"dilem": "remember/wake up (覚える/覚める) / To bring (持つ)",
"dim": "pain (苦しみ)",
"dis": "two people (二人) / Magic (魔法)",
"disigalm": "comical (滑稽)",
"dist": "forget (忘れる)",
"disverry": "magic words (魔法の言葉)",
"dizzle": "cracked/broken (割れる)",
"dizzlet": "splitted (割れる)",
"doe": "to lower down (下ろす)",
"doool": "vortex (渦)",
"dooolas": "whirling (渦巻き)",
"dooom": "deep (深い)",
"dooomlait": "deeply (深く)",
"dora": "darkness (闇)",
"doraid": "darkness (暗闇)",
"dorain": "dark (暗い)",
"dro": "one (一)",
"drone": "alone/Lonely (ひとり)",
"dronene": "All alone (独りぼっち)",
"droq": "bag (カバン)",
"dufaus": "reason (as in power to give reasons) (理性)",
"eadalam": "creator (創造主)",
"eala": "fall/Drip (滴る/落ちる)",
"easdriwd": "guillotine (ギロチン)",
"ebilinijes": "inorganic (無機質)",
"ebilinijeslait": "inorganicly (無機質に)",
"eclat": "sparkle (煌めき)",
"edal": "ground (地)",
"edie": "underground (地下)",
"edil": "robe (ローブ) / Each (ずつ)",
"editav": "perfect fit (ぴったり)",
"edlijtu": "to feel sorrow (憂う)",
"eem": "to have a feeling (気がする)",
"efa": "era (時代)",
"efiitlaw": "banquet (晩餐会)",
"efitu": "to Eat (食べる)",
"efok": "cough (咳)",
"egdrea": "to worship (祀る)",
"eid": "move (動く)",
"eidarit": "particle (粒子)",
"eide": "upper Ground (地中)",
"eilent": "frustrated (悔しい)",
"eiphinr": "gaze (眺める)",
"eist": "door (扉)",
"eiti": "next (次)",
"eitilait": "next place (next world) (新しい世界)",
"eivena": "withdrawal (撤回)",
"ekphie": "to fulfill (叶う)",
"ekphinols": "regret (未練)",
"elaisic": "today (今日)",
"elemie": "pain (痛み)",
"elay": "to come (来る)",
"elfalasia": "welcome (ようこそ)",
"elifiance": "to be helped (助かる)",
"eliisa": "herd (群れ)",
"elijsjelm": "spinal Cord (脊髄)",
"elize": "therefore/Because (だから)",
"ell": "to choose (選ぶ)",
"elled": "elevator",
"ellif": "to live (生きる)",
"ellift": "living (生きる事)",
"elquom": "attraction (引力)",
"elza": "feather (羽)",
"elzanoa": "featherless",
"emer": "lie (嘘)",
"emerne": "liar (噓つき)",
"emerneqls": "liars (噓つき)",
"emphi": "to miss",
"emsa": "grain (粒)",
"enaq": "wield (かざす)",
"endekta": "to admit (認める)",
"endyd": "to cast (かける)",
"ene": "person (人)",
"enebis": "human (人間)",
"enphil": "amber (琥珀)",
"enquif": "best (得意)",
"ensloadivi": "fairy (妖精)",
"entic": "with all one's might (思い切り)",
"entie": "ride (乗る)",
"entllphi": "to form has (告げる)",
"epkejla": "head (頭)",
"epkejlarche": "above one's head (頭上)",
"era": "earth (土)",
"eram": "clay (泥)",
"erlim": "long-lasting (永い)",
"es hai di": "trace of evidence (証跡)",
"es towai di": "brightness (赫赫)",
"es crai ni": "your Atonement (贖罪)",
"es grei ni lau": "destiny (宿運)",
"esc": "to pull out (抜く)",
"escolia": "funeral (葬列)",
"esto": "east (東)",
"estola": "tangle (絡みつく)",
"esp": "fragment (欠片/一部)",
"etuse": "to help (助ける)",
"etusyatt": "help (助け)",
"eugidha": "ugly (醜い)",
"evila": "adorable (愛惜しい)",
"evilaqq": "lizard (トカゲ)",
"ewgit": "to be Enough (足りる)",
"ewguiderie": "to torment (苦しめる)",
"ewol": "dull grey (鈍色/灰色)",
"vleitiad": "dull grey (鈍色/灰色)",
"fal": "go home (帰る)",
"falt": "homecoming (帰る)",
"falarle": "umbrella (傘)",
"falke": "quickly (早く)",
"faress": "it’s okay (大丈夫)",
"farc": "dye (染まる)",
"farley": "next (次)",
"farp": "round (丸い)",
"farsha": "resuscitation (蘇生)",
"fas": "color (色彩)",
"fassinir": "colorful (色とりどり)",
"fatasmoute": "tidying up (後片付け)",
"faye": "mirage (蜃気楼)",
"fea": "crawl (這う)",
"fei": "square Hatch (陣) / Ring (輪っか)",
"feid": "flutter down (舞い降りる)",
"feida": "fatal (致命的)",
"feikeed": "stab (刺す)",
"feila": "to put up (我慢する)",
"feilihna": "seahorse (海馬)",
"fel": "town (街)",
"felia": "to bear (耐える)",
"fellusia":　"interstellar ethers (星間エーテル)",
"fenklu": "cheeks (頬)",
"fete": "destiny (運命)",
"fetisileq": "to hail (呼応)",
"fiakli": "neck (首)",
"fie": "he (彼)",
"fiea": "dazzling (眩い)",
"fiela": "to fear (怖がる)",
"fiem": "(counter for thin objects) (枚)",
"fiesmes": "long ago (とうに)",
"fiiani": "deep breath (深呼吸をする)",
"fijnyaditt": "they (彼ら)",
"fikalat": "routine (ルーティーン)",
"filistea": "suffocating (息苦しい)",
"filshua": "stomach (お腹)",
"fimoa": "hide (隠す)",
"fin": "palm (手のひら)",
"finient":　"horizon (地平線)",
"finka": "by the Way (ところで)",
"finz": "end/to end (終わり/終わる)",
"finzie": "to end (終わらせる)",
"finza": "exit (出口)",
"fiola": "flower (花)",
"fiolaza": "bouquet (花束)",
"fimeles": "expression (表情)",
"fise": "to rub (擦る)",
"flasche": "vial/Flask (小瓶)",
"flea": "the people/things (もの)",
"fleekijt": "dimension (次元)",
"fleesie": "to swing (振る)",
"fliiad": "heal (癒える)",
"flojrie": "arrive (辿り着く)",
"floul": "goes around (巡る)",
"flous": "float (浮かぶ)",
"folqui": "quarrel (諍い)",
"folsiagol": "beast (獣)",
"folsiagolzid": "den (棲みか)",
"foly": "it’s okay (大丈夫)",
"forsip": "to give (あげる)",
"fouza": "nature (自然)",
"fouzanoa": "unnatural (fouza+noa)",
"fouzanoalait": "unnaturally (不自然に)",
"fouz": "(to pull) out (出す)",
"fraitalia": "start (始まり)",
"frait": "start/to start (始まる/はじまり)",
"fraitit": "start (始まりに)",
"frey": "happiness (幸福)",
"fotzob miistiel": "self-portrait (自画像)",
"fur": "throw away (捨てる)",
"galha": "lonely (寂しい)",
"anisia": "lonely (寂しい)",
"anisialait": "lonesomely",
"galm": "button (ボタン)",
"garei": "neuron (ニューロン)",
"garve": "to carve/engrave (刻む)",
"gent": "to stand (立てる)",
"gete": "new (新しい)",
"giinia": "golden (金色)",
"giidu": "black (黒)",
"giila": "sharp (object) (鋭い)",
"gleetz": "arrange (並ぶ)",
"glenzikle": "altar (祭壇)",
"gllind": "killing by running over (轢殺)",
"golk": "bone (骨)",
"golsilipt": "double-dealing (二枚舌)",
"goriis": "grave (深刻)",
"goss": "celebrate (祝福する)",
"gossim": "blessings (祝福)",
"gout": "but (だけど/でも)",
"graid": "memory (記憶)",
"grend": "justice (正義)",
"guadisijlam": "living Sacrifice (生贄)",
"guidial": "opposing (合わせ)",
"guit": "know (知る)",
"gelsiakuap": "to scoff (嘲る)",
"hait": "liberty/Freedom (自由)",
"haart": "to nod (頷く)",
"hal": "talk (話す)",
"hamilslay": "good Morning (おはよう)",
"haol": "hand (手)",
"haols": "both hands (両手)",
"haolm": "palm (手のひら)",
"haou": "hand (手)",
"harie": "remember (思い出す)",
"harmiy": "arouse (目が覚める/思い出す/思う)",
"harla": "hope (希望)",
"harledid": "to trample (踏む)",
"harmey": "think (想う)",
"haundi": "behave (お行儀をする)",
"haymate": "birthplace (故郷)",
"heart": "thought (想い)",
"hedijlyke": "chaos (混沌)",
"heela": "intravenous line (点滴)",
"heil": "roll (転がる)",
"heilim": "to call (呼ぶ)",
"heiliam": "saving a file (セーブ)",
"heimia": "to side with each other (付き合う)",
"heipe": "to shoulder (抱く)",
"heiss": "to smile (微笑む)",
"heivi": "to Bite down (噛み締める)",
"heizid": "innocent (あどけない)",
"helfigi": "short gap (狭間)",
"helgiek": "fang (牙)",
"hellm": "illusion/Dream (幻/夢)",
"hellmeila": "daydream (トロイメライ)",
"hellsijma": "phantom (幻影)",
"hendi": "ornament (装飾)",
"heridier": "two equal halves (真っ二つ)",
"hervisme": "countless (無数)",
"herz": "heart (心)",
"herches": "heart (anatomy) (心臓)",
"heridiji": "milky Way (銀河)",
"hesiq": "mess (ぐちゃぐちゃ)",
"hesiqlait": "messily (ぐちゃぐちゃに)",
"hesserie": "relief (救い)",
"hiele": "look! <interjection> (ほら)",
"age": "look! <interjection> (ほら)",
"hierti": "repeat (繰り返す)",
"hiip": "to cover (塗る)",
"histipri": "history (歴史)",
"historia": "history (歴史)",
"hol-": "(some words starting with that)",
"holo": "forgive (赦す)",
"holstia": "wish (願い)",
"holt": "regret (後悔)",
"holtica": "sin (罪)",
"holtit": "self-Remorse (自責の念)",
"holsiana": "reset (リセット)",
"hor": "hey! (よ！)",
"horiis": "to welcome/escort (迎える)",
"horlmaia": "formula (式)",
"hyerisq": "Hey (やあ)",
"hyula": "look up (仰ぐ)",
"hyune": "100",
"hyuz": "wind (風)",
"iar": "hear (聞く)",
"idem": "reduce Into",
"idial": "to fly and ride (飛び乗る)",
"ieha": "need (必要)",
"ignai": "never, nothing",
"iila": "girl (少女)",
"ijsya": "scent (香り/匂い)",
"ijti": "loud (高らか)",
"iladmea": "sooty (煤める)",
"ildrem": "civilization (文明)",
"ilfelie": "revenant (亡霊)",
"ilis": "rainbow (虹)",
"ilip": "to attach (つく)",
"ilqum": "ritual (儀式)",
"imiyl": "to go through (this way) (通る)",
"imiylt": "pushed through (抜け)",
"impihs": "to pay off (果たす)",
"in": "twilight (隙間) / acts like 真",
"ipsi": "arm (腕)",
"inay": "wait (待つ)",
"indi": "heavy (重い)",
"invalda": "summon (召喚)",
"invilsta": "doppelgänger (ドッペルゲンガー)",
"invilstaqls": "doppelgängers (ドッペルゲンガー)",
"irdliq": "judgement (審判)",
"isbalg": "baptism (洗礼)",
"ixche": "name (名)",
"jac": "dry (渇く)",
"jam": "agonizing (悩ましい)",
"jamiy": "unsewn (縫目がない)",
"jareic": "to wave (靡く)",
"jay": "to be sad (悲しむ)",
"jayt": "sad (jay+t)",
"jedreid": "to glorify (崇める)",
"jedleqnoa": "of no help/no use (役に立たない)",
"jered": "skin (皮)",
"jeridiq": "code (コード)",
"jesijne": "sage (賢人)",
"jiddle": "iron (鉄)",
"jilga": "back (背中)",
"joul": "hopeless (だめ)",
"jueid": "disgusted, had enough (うんざり)",
"kampiela": "compass (羅針盤)",
"katarle": "dweller (往人)",
"kelasaid": "scatter (撒く)",
"kelletta": "to use (使う)",
"kerla": "escape (逃げ出す)",
"kiila": "comet (彗星)",
"klattle": "to join (繋ぐ)",
"klardat": "shit (糞)",
"klautie": "nail (爪)",
"klatsia": "scattered (散らばる)",
"kleet": "diagonal (対角線)",
"klijka": "capsule (カプセル)",
"kllea": "cry (泣く)",
"klolsi": "rabbit (うさぎ)",
"klowdreus": "equal (平等)",
"klowdreuslait": "equally (平等に)",
"kolto": "bottom (底)",
"kopiit": "ruins (廃墟)",
"kopiita": "ruins (廃墟)",
"kopiitoli": "ruins (廃墟)",
"kre": "barefeet (裸足)",
"kreis": "to cross paths (交わる)",
"kremsa": "to frolic (戯れる)",
"krey": "very least/faint/little (せめて/小さな)",
"kuen": "to sacrifice (捧げる)",
"lackalatia": "good luck charm (おまじない)",
"laidiik": "spellbind (掛かる)",
"laila": "bird (鳥)",
"laiscall": "bell (鐘)",
"laiz": "future (未来) / To lose (失くす) / acts like だろう",
"laiziin": "route (航路)",
"la": "la (as in la la la)",
"lamb": "fruit (果実)",
"lamie": "grieve (嘆く)",
"lamiy": "to live (生きる)",
"lanai": "paradise (楽園)",
"lane": "to dash (駆ける)",
"laness": "to pass through (通り抜ける)",
"lans": "dance (踊る)",
"lansfidpiam": "ball (舞踏会)",
"laqq": "box (箱)",
"lar": "Towards (へ)",
"lazz": "life (命/生命)",
"leat": "unfinished (書きかける)",
"ledi": "to kidnap (連れ去る)",
"leife": "hollow (うつろ)",
"leim": "continuation (続き)",
"leimy": "let go (離れる/解放する)",
"lein": "to illuminate (照らす)",
"lenekle": "story (ストーリー)",
"leste": "come on! (さぁ)",
"ley": "continue (続く)",
"lieny": "let go (離す)",
"lidit": "more (もっと)",
"liin": "rain (雨)",
"liix": "absolution (赦し)",
"lili": "precious (切ない) / Just (だけ)",
"lilp": "butterfly (蝶)",
"linq": "anyone else (誰だって)",
"lipiq": "skin (皮膚)",
"liumd": "game (ゲーム)",
"liz": "to proceed (進む)",
"lizem": "to turn (time) (進める)",
"loast": "infinite (無窮)",
"loog": "long (長い)",
"loot": " for long (ずっと)",
"lootaria": "forever/eternal (ずっと/永遠)",
"lophala": "fish (魚)",
"loqcka": "distant (遠い)",
"luan": "to go (行く/込む)",
"luina":　"to yearn (焦がす)",
"luind":　"past (過去)",
"lusia": "light (光／明かり)",
"lushegand": "influence (威光)",
"lyck": "king (王様)",
"lyckto": "kingdom (王国)",
"lyckellana": "crown (王冠)",
"lytori": "throne (玉座)",
"madie": "lost (one’s way) (迷う)",
"madiendlea": "labyrinth (迷宮)",
"mage": "magic (魔法)",
"magene": "wizard (魔法使い)",
"mail": "clad (纏い)",
"mairu": "change (clothes) (着替える)",
"mane": "someday (いつか)",
"mariju": "to chase (追いかける)",
"mario": "to manipulate (操る)",
"mariotoriet": "marionette(傀儡/マリオネット)",
"marla": "dice (賽)",
"mazy": "maze (迷路)",
"meehellm": "daze (ぼうっと)",
"meele": "ocean (海)",
"meeti": "border (国境)",
"meidiep": "to give (与える)",
"meila": "to want (an item) (欲しい)",
"meisem": "scatter (散らかる)",
"meit": "head ofａcoin (表)",
"mejkl": "a great deal of (大きな)",
"melart": "sorry (ごめんなさい)",
"melineto": "bacteria (菌)",
"melnaid": "wither (萎れる)",
"melp": "blood (血液)",
"melpisia": "bloody (血まみれ)",
"melplist": "circulating Blood (血潮)",
"mezart": "milk (ミルク) / Needle (針)",
"mier": "more (もう)",
"mii": "i/Me (私)",
"miis": "myself (自分)",
"mijha": "purple (紫色)",
"mill": "us (私たち)",
"millarm": "to gaze upon (見つめる)",
"millte": "feeling (気)",
"millte": "feeling (気)",
"minai": "night Sky (夜空)",
"minelbli": "fixed star (恒星)",
"mineldari": "planet (惑星)",
"minelu": "star (星)",
"minelia": "moon (月)",
"minsty": "tomorrow (明日)",
"mirya": "apple (リンゴ)",
"mishalak": "legend (神話)",
"misiik": "to keep an item (預かる)",
"miz": "to become/ring (なる)",
"mizy": "mistake (間違い)",
"molda": "brain (脳)",
"mono": "monochromatic (モノクロ)",
"monodrama": "monodrama (モノドラマ)",
"mophen": "seven (7)",
"morhe": "mourn the dead (弔う)",
"mout": "beautiful/Charming (美しい/なまめかしい)",
"moutlait": "beautifuly/charmingly (mout+lait)",
"myahalke": "no matter how many times (何度も)",
"myte": "my (僕の)",
"nacc": "just now (たった今)",
"nache": "elementary (particles) (素)",
"naits": "here on (先)",
"niar": "childhood (times) (幼馴染)",
"nielatelea": "pictorial book (図鑑)",
"nilai": "fog (霧)",
"niims": "preterite/past (過去)",
"nita": "summer (夏)",
"noablem": "no one in sight (誰も…いない)",
"nol": "day (日/数)",
"noll": "do (やる)",
"nolm": "chant (唱える)",
"nouche": "night (夜)",
"nout": "go (ゆく)",
"ofelnti": "plankton (プランクトン)",
"og Perte": "stare (睨み合う)",
"ojdikkart": "curse (呪い)",
"olfeis": "take root (根を張る)",
"olis": "very, really (とても)",
"olistea": "very, really (とても)",
"olkemia": "rewrite (書き言える)",
"ola": "empty (がらんどう) / From (inside) (から)",
"olaio": "original (元)",
"oli": "place (所) / Attach to place when が/は is used. (indicates a place)",
"olipha": "place to go (行き場)",
"olca": "accumulate (積もる)",
"olista": "to overflow (溢れる)",
"olizenote": "something (何か)",
"olizes": "someone (誰か)",
"oll": "everyone (みんな)",
"olm": "blue (青)",
"olkei": "the most correct (一番正しい)",
"olseiph": "pride (誇り)",
"olte": "worry (気がする)",
"okititil": "edification (教化)",
"opsa": "a (certain) (或る)",
"optokia": "useless (無駄)",
"oracle": "miracle (奇跡)",
"orfag": "to get close (寄り添う)",
"ostel": "desert (砂漠)",
"oul": "big (大きい)",
"oulayz": "countless/Many (無数/幾つも)",
"paphileeta": "universe (宇宙)",
"pazz": "room (室)",
"peak": "footwear (履物)",
"peil": "put (置く)",
"peiti": "late (遅刻)",
"peitim": "keep inside (詰め込む)",
"pellsipia": "(ウロウロ)",
"pelto": "records (記録)",
"persona": "persona (ペルソナ)",
"phida": "distortion (歪み)",
"phina": "(About to) start (始まる)",
"phinglas": "idealistic thoughts (理想論)",
"phinglasene": "idealist (理想論者)",
"piala": "honest (清廉)",
"piero": "clown (ピエロ)",
"pieto": "transparent (透明)",
"piikle": "firmly (突く)",
"piisa": "very depths (奥底)",
"piisika": "to suffer (苦しむ)",
"piito": "sheep (羊)",
"pillusi": "to lose (失くす)",
"pisca": "cat (猫)",
"plenptie": "projector (映写機)",
"plar": "to become quiet (静まる)",
"plarli": "to pull (引っ張る)",
"plau": "to know (知る)",
"pleesa": "show (見せる)",
"plipha": "test (試験)",
"pliphalaine": "test subject (被験者)",
"pliphasoil": " test tube (試験管)",
"plist": "all of us (みな)",
"pllardki": "wonderful (素晴らしい)",
"polt": "feet (足元)",
"porta": "ship (船)",
"poul ail": "finally (結局)",
"pray": "sound (音)",
"preparat": "preperation (プレパラート)",
"prii": "drop (滴)",
"prifiel": "feel (判る)",
"prolen": "gaping (ぽっかり)",
"protia": "promise (約束)",
"prous": "pray (祈る)",
"prousia": "prayer (祈り)",
"pysiestia": "mission (使命)",
"qilie": "but still (それでも)",
"qualda": "stimulation (刺激)",
"quoltri": "to burn (焼き付ける)",
"quondlea": "castle (城)",
"quop": "series/system (系)",
"qlittit": "cracked (ひび割れる)",
"qtua": "mock (嘲る)",
"rait": "to Find (見つかる)",
"ran": "eye (目)",
"rance": "there is/are (ある)",
"rainya": "look, peep (見える)",
"ranya": "look, peep (臨む/見る/見える)",
"ranyabell": "to learn by watching others (見よう見まね)",
"ranyabellt": "learning by watching others (見よう見まね)",
"ranyastodd": "bleachers (観覧席)",
"rak": "person (人)",
"rakqls": "people (人)",
"rave": "overflow (滲む)",
"razzle": "break (落ちて割れる)",
"reiz": "to signal (告げる)",
"renz": "to expose to (晒す)",
"retuel": "bizarre/curious (奇々怪々/好奇)",
"rig": "flag (旗)",
"riikajta": "to receive (受ける)",
"rinasia": "born (孵化/生まれる)",
"rindou": "caress (撫でる)",
"ritto": "airborne (放つ)",
"roof": "hole (穴)",
"roofialaita": "tunnel (トンネル)",
"rook": "bid farewell (別れる)",
"rowt": "abyss (奈落)",
"rustie": "reflect (映る)",
"sai": "morning (朝)",
"sail": "sun (太陽)",
"salah": "shadow (影)",
"salie Proula": "reverend Monsignor (司祭さま)",
"samb": "at ease (済む)",
"san": "touch (触れる)",
"sanctue": "sanctuary (聖城)",
"sar": "same (同じ) / Together (一緒に) / In Accordance to (-通り)",
"sartain": "dawn (暁)",
"saray": "friend (友達)",
"sarp": "soup (スープ)",
"saryate": "together (一緒に)",
"ifa": "together (一緒に) / With (で)",
"saus": "millenium (千年)",
"saut": "voice (声)",
"scape": "paintbrush (絵の具)",
"scteus": "guardian (護り)",
"sctution": "protect (守る/護る)",
"seeda": "to guide (導く)",
"seedat": "guidance (導く)",
"seek": "say (云う)",
"seeka": "to flow (流す) / To reflect (映す)",
"seekle": "faint (仄か)",
"seema": "to realize/notice (気付く)",
"seiren": "sing (唄う)",
"selti": "meaning (意味)",
"sel": "true (本当)",
"selaf": "truth/reality (真実/現実)",
"selanya": "wander (彷徨う)",
"selate": "evening (宵)",
"selvell": "honest Feelings (本音)",
"selep": "skirt (スカート)",
"senju": "send (送る)",
"shalm": "being hurt (切ない)",
"sharla": "tree (樹)",
"shay": "fire (炎)",
"she": "holy (神聖)",
"shelim": "silent (静か)",
"shelimlait": "silently (静かに)",
"shelista": "world (世界)",
"shellarm": "holy Temple (神殿)",
"shellius": "god (神様)",
"shiita": "end (終わり)",
"siala": "song (唄)",
"sigik": "to turn away (逸らす)",
"sikid": "consciousness (意識)",
"siifii": "saliva (唾液)",
"siig": "to decide (決める)",
"sindip": "hyena (ハイエナ)",
"sinis": "left (左)",
"sipil": "to slip (すり抜ける)",
"siviliem": "instinct (本能)",
"sjylupe": "thwart (挫ける)",
"sjeid": "to rust (錆びる)",
"sjeidmea": "rusty (sjeid+mea)",
"sjeidveitea": "rusty red (赤錆びた)",
"skaid": "look at sky",
"skeem": "start (始める)",
"skelat": "mock (あざ笑う)",
"skie": "to cross (越える)",
"skima": "go under (潜る)",
"skyar": "to follow (做う)",
"slay": "road/Journey (道/旅)",
"sleetia": "corridor (回廊)",
"slialius": "to drain away (抜き取る)",
"sloa": "honey (蜂蜜)",
"sol": "smile (微笑)",
"sole": "soul (魂)",
"solfe": "unwind (ほどける)",
"solien": "sofa (ソファ)",
"solte": "behind (裏)",
"sou": "snow (雪)",
"spai": "welter (溺れる)",
"spay": "mirror (鏡)",
"speixem": "specimens (標本)",
"sphiep": "sphere (球)",
"spitia": "sphere (螺旋)",
"squa": "face (顔)",
"stache": "drawer (ドロワー)",
"staple": "staircase (階段)",
"staps": "to clap (叩く)",
"stea": "draw/Guide (描く/運ぶ)",
"stegraid": "revolving Lantern (走馬灯)",
"stei": "view (景色)",
"stica": "hold (breath) (止める)",
"stjpile": "to wipe (拭う)",
"stodd": "seat (席)",
"story": "story (物語)",
"storys": "story (物語)",
"sween": "sleep (眠る)",
"sweem": "sleep (眠る)",
"swiina": "wrap/cover(包む/纏う/覆う)",
"swinia": "shell (殻)",
"swormin": "take off (飛び込む)",
"sworntie": "put to sleep (眠らせる)",
"sy": "angel (天使)",
"syeilla": "angel (天使)",
"syarfi": "dress (ドレス)",
"syena": "apotheosis (神化)",
"synapse": "synapse (シナプス)",
"talis": "A long time (長い間)",
"tarn": "year (年)",
"taz": "time (時/頃)",
"tozlom": "time (時/頃)",
"teejt": "trap (閉じ込む)",
"tehomea": "depths/Abyss (深淵)",
"tella": "flow (流される)",
"telly": "to leave (something for someone) (預ける)",
"termz": "clock (時計)",
"theegie": "rage (怒り)",
"theek": "knife (ナイフ)",
"thloo": "oh my God (大変)",
"thuivili": "busily (忙しい)",
"tiag": "scream (叫ぶ)",
"ticcarm": "little by little (少しずつ)",
"ticcla": "glass (ガラス)",
"tigalm": "destroy/cover completely (潰す)",
"tiika": "to disturb (かき乱す)",
"tim": "lamp (灯)",
"tikelt": "right (すぐ)",
"tikk": "blood (血)",
"tit": "poem (詩)",
"tittri": "retina (瞳)",
"tleiket": "to organize (整理する)",
"tlli": "press (押す)",
"tollm": "spill out (零れだす)",
"tollti": "drip (滴る)",
"tone": "monster (怪獣) / Rear (背)",
"torch": "traffic Lights (信号機)",
"toriesta": "witch (魔女)",
"torjest": "kill (殺す)",
"torke": "to worship (礼拝)",
"toubi": "to Open (eyes) (開ける)",
"toup": "type (種類)",
"toys": "toys (おもちゃ)",
"traluki": "to be buried (埋もれる)",
"trane": "tear (泪/涙)",
"tri": "three (三)",
"trico": "too much (あんまり)",
"tuklt": "data (データ)",
"tvulei": "appearance (姿)",
"ullem": "depths (奥)",
"unharla": "chance (チャンス)",
"vakka": "to possess (取り憑く)",
"vaice": "witness (証人)",
"vala": "wall (壁)",
"veditt": "to preach (説く)",
"veida": "rolled number/ordinal number (目)",
"veilatoriet": "doll (人形)",
"veit": "red (赤い)",
"velidi": "cage (檻)",
"vellediola": "graveyard (墓場)",
"velsiam": "dirty (汚い)",
"venesene": "cluster (幽)",
"verde": "distorted (歪曲)",
"verse": "disappear (消え去る/消える)",
"sadiet": "disappear (消え去る/消える)",
"rata": "disappear (消え去る/消える)",
"ratatouille": "ratatouille (ラタトゥイユ)",
"verry": "word (言葉)",
"via": "journey (旅)",
"viazulu": "traveller (旅人)",
"viccla": "glass (ガラス)",
"vidd": "queen (女王)",
"viditt": "to preach (説く)",
"vielakaite": "lake (湖)",
"viin": "to Search (探す)",
"viizy": "bug (gaming term) (バグ)",
"vijg": "to be hungry for (飢える)",
"vilkt": "corpse (骸)",
"vindi": "bruise (痣)",
"vindiald": "to make a bruise (痣をつける)",
"vinelo": "winter (冬)",
"visini": "devil (悪魔)",
"vins": "evil (悪)",
"vinshellm": "nightmare (悪夢)",
"vinshellms": "nightmares (悪夢たち)",
"visc": "to know (知る)",
"vitui": "great (formal) (よろしい)",
"vivi": "born (燈る)",
"vleisa": "distance (彼方)",
"volp": "ghosts (お化け)",
"waltisala": "hymn (讃美歌)",
"way": "answer (答え)",
"ween": "end/limit (果て)",
"wedikarti": "to save (救う)",
"weilla": "rose (薔薇)",
"weika": "secret (秘密)",
"weliim": "melt (溶ける)",
"wely": "sink (沈む)",
"wend": "to swim (泳ぐ)",
"wendit": "swimming (泳ぐ)",
"wendiak": "giant (巨大)",
"wendiq": "to wear (around head area) (被る)",
"whiil": "white (白)",
"wihrind": "to wake up (醒める)",
"wiina": "sleep (眠り)",
"will": "heartbeat (鼓動)",
"wipt": "to throw (投げる)",
"wipsam": "line of Sight (視線)",
"wiziliq": "antimony (アンチノミー)",
"wizlad": "to play (an act/perform) (演じる)",
"wizladene": "performer (演者)",
"woli": "to bless (授かる)",
"wolme": "carpet (絨毯)",
"womphil": "swallow (飲み込む)",
"wond": "wound (傷)",
"wondist": "wound (傷)",
"wondidda": "pain (痛い)",
"xianya": "think (思う)",
"xlleidie": "ghost (幽霊)",
"yien": "passive conjugation (られ)",
"yiend": "passive conjugation (られ)",
"yiep": "please",
"phier": "please (お願い)",
"yiela": "give me (賜う)",
"yulleia": "gradually (ゆっくり)",
"yutul": "a day (一日)",
"yutulsinv": "everyday (毎日)",
"yuwlpie": "utopia (ユートピア)",
"zeit": "moment (時間)",
"zenoth": "sigh (溜め息)",
"zia": "me (僕)",
"zibilial": "rich Color (極彩色)",
"zill": "we (僕ら)",
"zillyte": "we (僕ら)",
"ziksii": "well-mannered (お行儀いい)",
"ziksiilait": "well-manneredly (お行儀よく)",
"ziok": "thunder (雷)",
"ziokla": "ptarmigan (雷鳥)",
"zote": "season (季節)",
"zyte": "my (僕の)",
"a": "1. And (if connecting two nouns together) 2. Interjectory phrase (at the beginning)/Imperative command",
"ah": "1. And (if connecting two nouns together) 2. Interjectory phrase (at the beginning)/Imperative command",
"geeg": "acts like 〜ている/続ける (Present participle conjugation)",
"aim": "(acts like くらい)",
"alan": "if (たら)",
"am": "finally (やっと)",
"amabell": "finally (ようやく)",
"amblu": "acts like など",
"arte": "(acts like 〜たり)",
"bis": "Here/it's/this (ここ/これ/この)",
"bisoli": "here (ここ)",
"bistie": "that kind of (こんな)",
"blem": "who (誰)",
"blemyte": "whose (誰の)",
"dia": "well then... (それでは)",
"dou": "(Humble Impreative) (んだ)",
"dikta": "(Humble Impreative) (んだ)",
"ditka": "dikta ?",
"edil": "each (ずつ)",
"em": "like (end ol) but structured backwards.",
"end": "and (if connecting more than two nouns together OR connecting two or more adjectives or numbers OR That, as in Days that I cried, mission that I failed)",
"endaqlt": "because (から)",
"eik": "too much (過ぎる)",
"elaind": "right/yes (そう)",
"elie": "until (まで)",
"endjulf": "because of that (そうして)",
"epie": "i’d rather (方がいい)",
"es": "and/then",
"en": "and/then",
"far": "(quoting verb) that",
"fevla": "why not... (どうだい)",
"fiqq": "careful (よく〜)",
"fiqqlait": "carefully",
"folme": "from (から)",
"forle": "before (前に)",
"hols": "(Expresses desire for something)",
"ied": "should better to (〜ば良い)",
"ieq": "as a... (...として)",
"iequim": "entirely (まるで)",
"iis": "(Japanese Causative Form)",
"ijlim": "when (after a long time)(ころ)",
"il": "to (に)",
"ild": "to (に)",
"ilek": "somehow (どうにかして)",
"iqyur": "(Honorific prefix used for postion higher than speaker) (さま)",
"iy": "(Sentence breaker, or topic marker)",
"imeila": "despite (ところで)",
"imm": "in (に/で)",
"imm": "in (に/で)",
"karna": "again (また)",
"kueip": "-en (〜にする)",
"koll": "current State (まま)",
"kulu": "can (Japanese Potential Form)",
"leidiq": "try to",
"len": "intransitive modifier (落とす -> 落ちる)",
"lef": "like (みたい/よう)",
"lend": "are (Interrogative) (か)",
"liaphi": "(Neutral Honorific) (さん)",
"lid": "acts like 真",
"in": "acts like 真",
"lili": "just (だけ)",
"lim": "under (下)",
"likti": "just (ただ)",
"lishe": "let’s (Japanese volitional form)",
"loosya": "every/even (すら)",
"lqll": "(Currently unknown, but possibly used to indicate relatives)",
"mei": "the (relating to deity or high figure)",
"mols": "only (だけ)",
"nai": "not a... (無い)",
"neu": "nor (ない)",
"noa": "prefix of nothingness (-less) (無)(Note: some words have Noa appear as a suffix)",
"note": "thing (こと)",
"o": "am, is, are, was, were, might be, etc. (Usually dropped)",
"ob": "(Past participle conjugation)",
"occia": "even if (だって)",
"ofa": "(Possessive counter, used to prevent frequent use of current pronoun)",
"ol": "was, were (Past modifier)",
"ola": "from (inside) (から)",
"olfe": "acts like か(used for asking details with question word (i.e. 5W1H))",
"oltia": "that kind of (そんな)",
"olzy": "must (なくちゃ)なくちゃ)",
"ord": "by (something) / All (the way) (as in 全〜)",
"osa": "will be/still (まだ)",
"ou": "of the (acts like の (with person/people being the modified), but structured backwards)",
"pileknoa": "no matter (どれだけ…も)",
"plousa": "(Counter for occurrences) (度)",
"poa": "(Counter for small animals) (匹)",
"poet": "please (don’t) (ないで)",
"poetklar": "while (ながら)",
"poetolt": "in the end / End result (結局)",
"porsa": "to the full range, as much as (だけ)",
"poutie": "when/if (と/なら)",
"qleea": "completely (〜てしまう)",
"qleel": "should (〜てしまおうか)",
"imblu": "completely (〜てしまった)",
"qls": "suffix to indicate plurality (たち)",
"queit": "even though (のに)",
"roa": "even though (のに)",
"ra": "will be (future tense)",
"rie": "eventually (やがて)",
"sar": "in Accordance to (-通り)",
"sarga": "sky/space (空/大空/宙)",
"sii": "right/y'know (ね)",
"sip": "(acts like のさ)",
"shelta": "surely (きっと)",
"foul": "surely (きっと)",
"ticca": "a bit (少し)",
"tiisa": "it seems...",
"tie": "inside (when it’s topical) (には)",
"tou": "want (〜たい)",
"nadi": "want (〜たい)",
"tou": "even with (Vた + って)",
"twiik": "that (あの)",
"veis": "among (間)",
"velaiye": "i plan to (つもり)",
"vell": "1. No matter what (必ず) (Usually dropped in translation to indicate a condition that should be met) 2. Acts like も(ない)/ことのない 3. Likely to (だろう)",
"wasiim": "why (どうして)",
"weil": "inside (で)",
"well": "(Extent of time)(【こ・そ・あ】れほど)",
"wilenq": "how (なんて〜)",
"wimb": "however (ただし)",
"xaide": "that (Archaic) (彼の)",
"xia": "before a noun: That (それ/その) Before a verb, context is about past: (Acts like 〜てしまう) Before a verb, context is about near future: To come… (〜てくる)",
"xiaoli": "there (そこ)",
"xieti": "on that time (その時)",
"yiele": "not (ことのなかった)",
"zel": "what (何)",
"alia": "quite a...",
"isiam": "(verb) Back (〜返す)",
"it": "(turns a verb to an adjective)",
"jima": "(Acts like 〜てきた)",
"lait": "to modify an adjective to adverb (-ly)",
"lea": "verb to adjective",
"mea": "verb to adjective",
"ea": "verb to adjective",
"ll": "seems (Vます + ～そう)",
"oli": "attach to place when が/は is used. (indicates a place)",
"s": "suffix used to pluralize (pro)noun (たち)",
"soil": "suffix used to modify an activity to an object relating to it (-管)",
"t": "gerund modifier (事/delete する) (does not apply to all verbs)",
"tea": "(Harsh emphasis)",
"mia": "to match with each other (～合う)",
"ne": "suffix for a person being/doing something (人/者)",
"yatt": "(to turn a verb into a noun without adding -ing, only works on certain verbs.",
"yur": "add honorific prefix to previous word (お〜)(If ends on a silent letter that will be omitted.)",
"voi": "may be (かもしれない)"
};