const dico = {
"Aasye": "To ascend (昇る)",
"Abelu": "To begin to unwrap (ほころぶ)",
"Acary": "Apocalypse (黙示)",
"Advelses": "Loop-de-loop (宙返り)",
"Aidaltia": "To strangle (絞める)",
"Aihel": "To exist (いる/ある)",
"Ail": "Full (満/全て)",
"Ailes": "To resemble (似ている)",
"Ail Scape": "Everywhere (どこへだって)",
"Ailjfa": "To be satisfied (満たす)",
"Aishellm": "Distress (無我夢中)",
"Aisia Mia": "Feeling (感覚)",
"Ait": "to cut (切る)",
"Ajarla": "To bear (抱える)",
"Aka": "Water (水)",
"Akaite": "Fluid (～液)",
"Ald": "to put (つける)",
"Alger": "Crowd (雑踏)",
"Alista": "Create (創る)",
"Allss": "Eyelid (目蓋)",
"Alvete": "Welcome (ようこそ)",
"Amb": "Strong (強い)",
"Entilk": "Strong (強い)",
"Ame": "Child (子)",
"Amejdimer": "Fetus (胎児)",
"Amie": "Love (愛)",
"Amil": "Wake up (目を覚める)",
"Amiy": "to love (愛する)",
"Amnist": "Yesterday (昨日)",
"Andauraspray": "Cacophony (不協和音)",
"Ani": "A (一 (counter))",
"Anie/Piino": "Breath (息)",
"Antakt": "To dive (潜る)",
"Anyahel": "Combine to one place (全てはひとつになって)",
"Aola": "Now (今)",
"Apeilf Yullk": "Floating (揺蕩う)",
"Apka": "Rope (ロープ)",
"Apnesia": "Visit (訪れる) / Certainly (確かに)",
"Aprout": "Guarantee (保障)",
"Arche": "Top (上)",
"Arel": "Streak (勿怪)",
"Ardand": "Skill (技)",
"Ariqlowt": "Reason/Theory (理) (romanized as “kotowari”)",
"Arla": "White (白い)",
"Arlistielim": "All things (万象)",
"Ark": "Celestial (天)",
"Arriziam": "to head towards (向かう)",
"Arsa": "Ash (灰)",
"Arth": "To remain",
"Arupe": "Ancient (古代)",
"Ary": "To go through (抜ける)",
"Asta": "Electricity (電気)",
"Atherty": "Evolution (進化)",
"Awdrom": "Order/Command (命令)",
"Awslijvikt": "Plotted out (筋書き通り)",
"Awlst": "Ready (準備する)",
"Awter": "To meet (旅をする/逢う)",
"Bai": "Already/Not anymore (もう)",
"Baly": "Always (いつだって)",
"Bell": "Remember (覚える)",
"Belqua": "to get packed, to get crowded (込む)",
"Belzebav": "Beelzebub (ベルゼブブ)",
"Berte": "Mountain (山)",
"Biibell": "Irregular (不揃い)",
"Bip": "Insect (虫)",
"Bipeid": "to Wriggle (蠢く)",
"Blawpelee": "Popcorn (ポップコーン)",
"Bllink": "Blink (明滅する)",
"Brai": "Inside (中)",
"Brait": "Open/Breath (開ける/息吹)",
"Tordu": "Open/Breath (開ける/息吹)",
"Briss": "Grow apart (すれ違う)",
"Brou": "Cloud (雲)",
"Brous": "Storm (嵐)",
"Canvie": "Once more (もう一度) / Change (変わる)",
"Caren": "Silence (静寂)",
"Cate": "Walk (歩く)/ Glorify (謳歌する)",
"Ceeka": "Bar (格子)",
"Cees": "Ice wall (氷壁) / Pale Blue (水色)　/ Frozen (凍る)",
"Chail": "Key (鍵)",
"Challen": "Echo (響く)",
"Circus": "Circus",
"Clooshe": "Close (閉める)",
"Clooshela": "Closet (クローゼット)",
"Cloud": "You (あなた)",
"Cloudyte": "You (あなた)",
"Cliid": "Fall (from sky) (降りる/注ぐ)",
"Cobbs": "Fly (蠅)",
"Colista": "Seek (求める) / to beg (乞う)",
"Coll": "Body (体)",
"Colt": "Cold (冷たい)",
"Crai": "You (君)",
"Crute": "Intersection (交差点)",
"Dangli": "To get soaked (漬ける)",
"Darlitte": "Curtain (of show) (幕)",
"Deank": "Thanks (感謝/ありがとう)",
"Deet": "Reach (届く)",
"Dex": "Right (右)",
"Di": "Two (二)",
"Dialiff": "Die (死ぬ/息絶える)",
"Dialoss": "Wither (枯れる)",
"Diazz": "Twins",
"Dibytt": "To be clouded with (覆う)",
"Digris": "to obtain (手にする)",
"Dijap": "déjà vu (デジャヴ)",
"Dijsya": "to prevent (阻む)",
"Dikteb": "to construct (構築する)",
"Dikti": "Unfortunate (不幸)",
"Dikzim": "To be intoxicated (酔い痴れる)",
"Dilem": "reason/Purpose (理由/所以/ため)",
"Arsia": "reason/Purpose (理由/所以/ため)",
"Dilem": "Remember/wake up (覚える/覚める) / To bring (持つ)",
"Dim": "Pain (苦しみ)",
"Dis": "Two people (二人) / Magic (魔法)",
"Disigalm": "Comical (滑稽)",
"Dist": "Forget (忘れる)",
"Disverry": "Magic words (魔法の言葉)",
"Dizzle": "cracked/broken (割れる)",
"Doe": "to lower down (下ろす)",
"Doool": "Vortex (渦)",
"Dooolas": "Whirling (渦巻き)",
"Dooom": "Deep (深い)",
"Dora": "Darkness (闇)",
"Dro": "One (一)",
"Drone": "Alone/Lonely (ひとり)",
"Droq": "Bag (カバン)",
"Dufaus": "Reason (as in power to give reasons) (理性)",
"Eadalam": "Creator (創造主)",
"Eala": "Fall/Drip (滴る/落ちる)",
"Ebilinijes": "Inorganic (無機質)",
"Eclat": "Sparkle (煌めき)",
"Edal": "Ground (地)",
"Edie": "Underground (地下)",
"Edil": "Robe (ローブ)",
"Editav": "perfect fit (ぴったり)",
"Edlijtu": "To feel sorrow (憂う)",
"Eem": "To have a feeling (気がする)",
"Efa": "Era (時代)",
"Efiitlaw": "Banquet (晩餐会)",
"Efitu": "to Eat (食べる)",
"Efok": "Cough (咳)",
"Egdrea": "To worship (祀る)",
"Eid": "Move (動く)",
"Eidarit": "Particle (粒子)",
"Eide": "Upper Ground (地中)",
"Eilent": "Frustrated (悔しい)",
"Eiphinr": "Gaze (眺める)",
"Eist": "Door (扉)",
"Eiti": "Next (次)",
"Eivena": "Withdrawal (撤回)",
"Ekphie": "To fulfill (叶う)",
"Ekphinols": "regret (未練)",
"Elaisic": "Today (今日)",
"Elemie": "Pain (痛み)",
"Elay": "To come (来る)",
"Elfalasia": "Welcome (ようこそ)",
"Elifiance": "To be helped (助かる)",
"Eliisa": "Herd (群れ)",
"Elijsjelm": "Spinal Cord (脊髄)",
"Elize": "Therefore/Because (だから)",
"Ell": "To choose (選ぶ)",
"Elled": "Elevator",
"Ellif": "To live (生きる)",
"Elquom": "Attraction (引力)",
"Elza": "Feather (羽)",
"Emer": "Lie (嘘)",
"Emerne": "Liar (噓つき)",
"Emphi": "To miss",
"Emsa": "Grain (粒)",
"Enaq": "Wield (かざす)",
"Endekta": "To admit (認める)",
"Endyd": "To cast (かける)",
"Ene": "Person (人)",
"Enebis": "Human (人間)",
"Enphil": "Amber (琥珀)",
"Enquif": "Best (得意)",
"Ensloadivi": "Fairy (妖精)",
"Entic": "With all one's might (思い切り)",
"Entie": "Ride (乗る)",
"Entllphi": "To form has (告げる)",
"Epkejla": "Head (頭)",
"Era": "Earth (土)",
"Eram": "Clay (泥)",
"Erlim": "Long-lasting (永い)",
"es hai di": "Trace of evidence (証跡)",
"es towai di": "Brightness (赫赫)",
"es crai ni": "Your Atonement (贖罪)",
"es grei ni lau": "destiny (宿運)",
"Esc": "To pull out (抜く)",
"Escolia": "Funeral (葬列)",
"Esto": "East (東)",
"Estola": "Tangle (絡みつく)",
"Esp": "Fragment (欠片/一部)",
"Etuse": "Help (助ける)",
"Eugidha": "Ugly (醜い)",
"Evila": "Adorable (愛惜しい)",
"Evilaqq": "Lizard (トカゲ)",
"Ewgit": "To be Enough (足りる)",
"Ewguiderie": "To torment (苦しめる)",
"Ewol": "Dull grey (鈍色/灰色)",
"Vleitiad": "Dull grey (鈍色/灰色)",
"Fal": "Go home (帰る)",
"Falarle": "Umbrella (傘)",
"Falke": "Quickly (早く)",
"Faress": "It’s okay (大丈夫)",
"Farc": "Dye (染まる)",
"Farley": "Next (次)",
"Farp": "Round (丸い)",
"Farsha": "Resuscitation (蘇生)",
"Fas": "Color (色彩)",
"Fassinir": "Colorful (色とりどり)",
"Fatasmoute": "Tidying up (後片付け)",
"Faye": "Mirage (蜃気楼)",
"Fea": "Crawl (這う)",
"Fei": "Square Hatch (陣) / Ring (輪っか)",
"Feid": "Flutter down (舞い降りる)",
"Feida": "Fatal (致命的)",
"Feikeed": "Stab (刺す)",
"Feila": "To put up (我慢する)",
"Feilihna": "Seahorse (海馬)",
"Fel": "Town (街)",
"Felia": "To bear (耐える)",
"Fellusia":　"Interstellar ethers (星間エーテル)",
"Fenklu": "Cheeks (頬)",
"Fete": "Destiny (運命)",
"Fetisileq": "To hail (呼応)",
"Fiakli": "Neck (首)",
"Fie": "He (彼)",
"Fiea": "Dazzling (眩い)",
"Fiela": "To fear (怖がる)",
"Fiem": "(counter for thin objects) (枚)",
"Fiesmes": "Long ago (とうに)",
"Fiiani": "Deep breath (深呼吸をする)",
"Fijnyaditt": "They (彼ら)",
"Fikalat": "routine (ルーティーン)",
"Filistea": "Suffocating (息苦しい)",
"Filshua": "Stomach (お腹)",
"Fimoa": "Hide (隠す)",
"Fin": "Palm (手のひら)",
"Finient":　"Horizon (地平線)",
"Finka": "By the Way (ところで)",
"Finz": "End (終わり)",
"Finzie": "To end (終わらせる)",
"Finza": "Exit (出口)",
"Fiola": "Flower (花)",
"Fiolaza": "Bouquet (花束)",
"Fimeles": "Expression (表情)",
"Fise": "To rub (擦る)",
"Flasche": "Vial/Flask (小瓶)",
"Flea": "The people/things (もの)",
"Fleekijt": "Dimension (次元)",
"Fleesie": "to swing (振る)",
"Fliiad": "Heal (癒える)",
"Flojrie": "Arrive (辿り着く)",
"Floul": "Goes around (巡る)",
"Flous": "Float (浮かぶ)",
"Folqui": "Quarrel (諍い)",
"Folsiagol": "Beast (獣)",
"Folsiagolzid": "Den (棲みか)",
"Foly": "It’s okay (大丈夫)",
"Forsip": "To give (あげる)",
"Fouja": "Nature (自然)",
"Fouz": "(to pull) out (出す)",
"Frait": "Start (始まる)",
"Frey": "Happiness (幸福)",
"Fotzob Miistiel": "self-portrait (自画像)",
"Fur": "Throw away (捨てる)",
"Galha": "Lonely (寂しい)",
"Anisia": "Lonely (寂しい)",
"Galm": "Button (ボタン)",
"Garei": "Neuron (ニューロン)",
"Garve": "To carve/engrave (刻む)",
"Gent": "To build (立てる)",
"Gete": "New (新しい)",
"Gent": "Golden (金色)",
"Giinia": "Golden (金色)",
"Giidu": "Black (黒)",
"Giila": "sharp (object) (鋭い)",
"Gleetz": "Arrange (並ぶ)",
"Glenzikle": "Altar (祭壇)",
"Gllind": "killing by running over (轢殺)",
"Golk": "Bone (骨)",
"Golsilipt": "Double-dealing (二枚舌)",
"Goriis": "Grave (深刻)",
"Goss": "Celebrate (祝福する)",
"Gout": "But (だけど/でも)",
"Graid": "Memory (記憶)",
"Grend": "Justice (正義)",
"Guadisijlam": "Living Sacrifice (生贄)",
"Guidial": "Opposing (合わせ)",
"Guit": "Know (知る)",
"Hait": "Liberty/Freedom (自由)",
"Haart": "To nod (頷く)",
"Hal": "Talk (話す)",
"Hamislay": "Good Morning (おはよう)",
"Haol": "Hand (手)",
"Haolm": "Palm (手のひら)",
"Harie": "Remember (思い出す)",
"Harmiy": "Remember (思い出す)",
"Harla": "hope (希望)",
"Harmey": "Think (想う)",
"Haundi": "Behave (お行儀をする)",
"Haymate": "Birthplace (故郷)",
"Heart": "Thought (想い)",
"Hedijlyke": "Chaos (混沌)",
"Heela": "Intravenous line (点滴)",
"Heil": "Roll (転がる)",
"Heilim": "To call (呼ぶ)",
"Heiliam": "Saving a file (セーブ)",
"Heimia": "To side with each other (付き合う)",
"Heipe": "To shoulder (抱く)",
"Heiss": "to smile (微笑む)",
"Heivi": "to Bite down (噛み締める)",
"Heizid": "Innocent (あどけない)",
"Helfigi": "Short gap (狭間)",
"Helgiek": "Fang (牙)",
"Hellm": "Illusion/Dream (幻/夢)",
"Hellmeila": "Daydream (トロイメライ)",
"Hellsijma": "Phantom (幻影)",
"Hendi": "Ornament (装飾)",
"Heridier": "Two equal halves (真っ二つ)",
"Hervisme": "Countless (無数)",
"Herz": "Heart (心)",
"Herches": "Heart (anatomy) (心臓)",
"Heridiji": "Milky Way (銀河)",
"Hiele": "Look! <interjection> (ほら)",
"Age": "Look! <interjection> (ほら)",
"Hierti": "repeat (繰り返す)",
"Hiip": "To cover (塗る)",
"Historia": "History (歴史)",
"Hol-": "(some words starting with that)",
"Holo": "Forgive (赦す)",
"Holstia": "Wish (願い)",
"Holt": "Regret (後悔)",
"Holtica": "Sin (罪)",
"Holtit": "Self-Remorse (自責の念)",
"Holsiana": "Reset (リセット)",
"Hor": "Hey! (よ！)",
"Horiis": "To welcome/escort (迎える)",
"Horlmaia": "Formula (式)",
"Hyula": "Look up (仰ぐ)",
"Hyune": "100",
"Hyuz": "Wind (風)",
"Iar": "Hear (聞く)",
"Idem": "Reduce Into",
"Idial": "To fly and ride (飛び乗る)",
"Ieha": "Need (必要)",
"Ignai": "never, nothing",
"Iila": "Girl (少女)",
"Ijsya": "Scent (香り/匂い)",
"Ijti": "Loud (高らか)",
"Iladmea": "Sooty (煤める)",
"Ildrem": "Civilization (文明)",
"Ilfelie": "Revenant (亡霊)",
"Ilis": "Rainbow (虹)",
"Ilip": "To attach (つく)",
"Ilqum": "Ritual (儀式)",
"Imiyl": "To go through (this way) (通る)",
"Imiylt": "Pushed through (抜け)",
"Impihs": "To pay off (果たす)",
"In": "Twilight (隙間)",
"Ipsi": "Arm (腕)",
"Inay": "Wait (待つ)",
"Indi": "Heavy (重い)",
"Invalda": "Summon (召喚)",
"Irdliq": "Judgement (審判)",
"Isbalf": "Baptism (洗礼)",
"Ixche": "Name (名)",
"Jac": "Dry (渇く)",
"Jam": "Agonizing (悩ましい)",
"Jamiy": "Unsewn (縫目がない)",
"Jareic": "To wave (靡く)",
"Jay": "To be sad (悲しむ)",
"Jedreid": "To glorify (崇める)",
"Jered": "skin (皮)",
"Jeridiq": "Code (コード)",
"Jesijne": "Sage (賢人)",
"Jiddle": "Iron (鉄)",
"Jilga": "Back (背中)",
"Joul": "Hopeless (だめ)",
"Jueid": "Disgusted, had enough (うんざり)",
"Kampiela": "Compass (羅針盤)",
"Katarle": "Dweller (往人)",
"Kelasaid": "Scatter (撒く)",
"Kelletta": "Use (使う)",
"Kerla": "Escape (逃げ出す)",
"Kiila": "Comet (彗星)",
"Klattle": "To join (繋ぐ)",
"Klautie": "Nail (爪)",
"Klar Tikelt": "Right around (すぐ)",
"Klatsia": "Scattered (散らばる)",
"Kleet": "Diagonal (対角線)",
"Klijka": "Capsule (カプセル)",
"Kllea": "Cry (泣く)",
"Klolsi": "Rabbit (うさぎ)",
"Klowdreus": "Equal (平等)",
"Kolto": "bottom (底)",
"Kopiit": "Ruins (廃墟)",
"Kopiita": "Ruins (廃墟)",
"Kopiitoli": "Ruins (廃墟)",
"Kre": "Barefeet (裸足)",
"Kreis": "To cross paths (交わる)",
"Kremsa": "To frolic (戯れる)",
"Krey": "Very least/faint/little (せめて/小さな)",
"Kuen": "to sacrifice (捧げる)",
"Laidiik": "Spellbind (掛かる)",
"Laila": "Bird (鳥)",
"Laiscall": "Bell (鐘)",
"Laiz": "Future (未来) / To lose (失くす)",
"Laiziin": "Route (航路)",
"Lamb": "Fruit (果実)",
"Lamie": "Grieve (嘆く)",
"Lamiy": "To live (生きる)",
"Lanai": "Paradise (楽園)",
"Lane": "To dash (駆ける)",
"Laness": "To pass through (通り抜ける)",
"Lans": "Dance (踊る)",
"Lansfidpiam": "Ball (舞踏会)",
"Laqq": "Box (箱)",
"Lar": "Left (左)",
"Lazz": "Life (命/生命)",
"Leat": "Unfinished (書きかける)",
"Ledi": "To kidnap (連れ去る)",
"Leife": "Hollow (うつろ)",
"Leim": "Continuation (続き)",
"Leimy": "Let go (離れる/解放する)",
"Lein": "To illuminate (照らす)",
"Lenekle": "Story (ストーリー)",
"Leste": "Come on! (さぁ)",
"Ley": "Continue (続く)",
"Lieny": "Let go (離す)",
"Lidit": "More (もっと)",
"Liin": "Rain (雨)",
"Liix": "Absolution (赦し)",
"Lili": "Precious (切ない)",
"Lilp": "Butterfly (蝶)",
"Linq": "Anyone else (誰だって)",
"Lipiq": "Skin (皮膚)",
"Liumd": "Game (ゲーム)",
"Liz": "To proceed (進む)",
"Lizem": "To turn (time) (進める)",
"Loast": "Infinite (無窮)",
"Loog": "Long (長い)",
"Lootaria": "Eternal (永遠, usually dropped in translation)",
"Lophala": "Fish (魚)",
"Loqcka": "Distant (遠い)",
"Luan": "to go/stand (行く/立つ/込む)",
"Luina":　"To yearn (焦がす)",
"Lusia": "Light (光／明かり)",
"Lushegand": "Influence (威光)",
"Lyck": "King (王様)",
"Lyckto": "Kingdom (王国)",
"Lyckellana": "Crown (王冠)",
"Lytori": "throne (玉座)",
"Madie": "Lost (one’s way) (迷う)",
"Madiendlea": "Labyrinth (迷宮)",
"Magene": "Wizard (魔法使い)",
"Mail": "Clad (纏い)",
"Mairu": "Change (clothes) (着替える)",
"Mane": "Someday (いつか)",
"Mariju": "To chase (追いかける)",
"Mario": "To manipulate (操る)",
"Mariotoriet": "Marionette/Puppetmaster (傀儡)",
"Marla": "Di(c)e (賽)",
"Mazy": "Maze (迷路)",
"Meehellm": "Daze (ぼうっと)",
"Meele": "Ocean (海)",
"Meeti": "Border (国境)",
"Meidiep": "To give (与える)",
"Meila": "To want (an item) (欲しい)",
"Meisem": "Scatter (散らかる)",
"Meit": "Head of a coin (表)",
"Mejkl": "A great deal of (大きな)",
"Melart": "Sorry (ごめんなさい)",
"Melineto": "Bacteria (菌)",
"Melnaid": "Wither (萎れる)",
"Melp": "Blood (血液)",
"Melpisia": "Bloody (血まみれ)",
"Melplist": "Circulating Blood (血潮)",
"Mezart": "Milk (ミルク) / Needle (針)",
"Mier": "More (もう)",
"Mii": "I/Me (私)",
"Miis": "Myself (自分)",
"Mijha": "Purple (紫色)",
"Mill": "Us (私たち)",
"Millarm": "To gaze upon (見つめる)",
"Millte": "Feeling (気)",
"Millte": "Feeling (気)",
"Minai": "Night Sky (夜空)",
"Minelbli": "Fixed star (恒星)",
"Mineldari": "Planet (惑星)",
"Minelu": "Star (星)",
"Minsty": "Tomorrow (明日)",
"Mirya": "Apple (リンゴ)",
"Mishalak": "Legend (神話)",
"Misiik": "To keep an item (預かる)",
"Miz": "To become/ring (なる)",
"Mizy": "Mistake (間違い)",
"Molda": "Brain (脳)",
"Mono": "Monochromatic (モノクロ)",
"Monodrama": "Monodrama (モノドラマ)",
"Mophen": "Seven (7)",
"Morhe": "Mourn the dead (弔う)",
"Mout": "Beautiful/Charming (美しい/なまめかしい)",
"Myahalke": "No matter how many times (何度も)",
"Myte": "My (one’s own body part)",
"Nacc": "Just now (たった今)",
"Nache": "Elementary (particles) (素)",
"Naits": "Here on (先)",
"Niar": "Childhood (times) (幼馴染)",
"Nielatelea": "Pictorial book (図鑑)",
"Nilai": "Fog (霧)",
"Niims": "Preterite (帰りたい過去)",
"Nita": "Summer (夏)",
"Noablem": "No one in sight (誰も…いない)",
"Nol": "Day (日/数)",
"Noll": "Do (やる)",
"Nolm": "Chant (唱える)",
"Nouche": "Night (夜)",
"Nout": "Go (ゆく)",
"Ofelnti": "Plankton (プランクトン)",
"Og Perte": "Stare (睨み合う)",
"Ojdillart": "Curse (呪い)",
"Olfeis": "Take root (根を張る)",
"Olis": "Very, really (とても)",
"Olistea": "Very, really (とても)",
"Olkemia": "Rewrite (書き言える)",
"Ola": "Empty (がらんどう)",
"Olaio": "Original (元)",
"Oli": "Place (所)",
"Olipha": "Place to go (行き場)",
"Olca": "Accumulate (積もる)",
"Olista": "To overflow (溢れる)",
"Olizenote": "Something (何か)",
"Olizes": "Someone (誰か)",
"Oll": "Everyone (みんな)",
"Olm": "Blue (青)",
"Olkei": "The most correct (一番正しい)",
"Olseiph": "Pride (誇り)",
"Olte": "Worry (気がする)",
"Okititil": "Edification (教化)",
"Opsa": "A (certain) (或る)",
"Optokia": "Useless (無駄)",
"Oracle": "Miracle (奇跡)",
"Orfag": "To get close (寄り添う)",
"Ostel": "Desert (砂漠)",
"Oul": "Big (大きい)",
"Oulayz": "Countless/Many (無数/幾つも)",
"Paphileeta": "Universe (宇宙)",
"Pazz": "Room (室)",
"Peak": "Footwear (履物)",
"Peil": "Put (置く)",
"Peiti": "Late (遅刻)",
"Peitim": "Keep inside (詰め込む)",
"Pellsipia": "(ウロウロ)",
"Pelto": "Records (記録)",
"Persona": "Persona (ペルソナ)",
"Phida": "Distortion (歪み)",
"Phina": "(About to) start (始まる)",
"Phinglas": "Idealistic thoughts (理想論)",
"Piala": "Honest (清廉)",
"Piero": "Clown (ピエロ)",
"Pieto": "Transparent (透明)",
"Piikle": "Firmly (突く)",
"Piisa": "Very depths (奥底)",
"Piisika": "To suffer (苦しむ)",
"Piito": "Sheep (羊)",
"Pillusi": "To lose (失くす)",
"Pisca": "Cat (猫)",
"Plenptie": "Projector (映写機)",
"Plar": "To become quiet (静まる)",
"Plarli": "To pull (引っ張る)",
"Plau": "To know (知る)",
"Pleesa": "Show (見せる)",
"Plipha": "Test (試験)",
"Plist": "All of us (みな)",
"Pllardki": "Wonderful (素晴らしい)",
"Polt": "Feet (足元)",
"Porta": "Ship (船)",
"Poul ail": "Finally (結局)",
"Pray": "Sound (音)",
"Preparat": "Preperation (プレパラート)",
"Prii": "Drop (滴)",
"Prifiel": "Feel (判る)",
"Prolen": "Gaping (ぽっかり)",
"Prous": "Pray (祈る)",
"Pysiestia": "Mission (使命)",
"Qilie": "But still (それでも)",
"Qualda": "Stimulation (刺激)",
"Quoltri": "To burn (焼き付ける)",
"Quondlea": "Castle (城)",
"Quop": "Series/system (系)",
"Qlittit": "Cracked (ひび割れる)",
"Qtua": "Mock (嘲る)",
"Gelsiaku": "Mock (嘲る)",
"Rait": "To Find (見つかる)",
"Ran": "Eye (目)",
"Rance": "There is/are (ある)",
"Ranya": "look, peep (臨む/見る)",
"Rak": "Person (人)",
"Rave": "Overflow (滲む)",
"Razzle": "Break (落ちて割れる)",
"Reiz": "To signal (告げる)",
"Renz": "To expose to (晒す)",
"Retuel": "Bizarre (奇々怪々)",
"Rig": "Flag (旗)",
"Riikajta": "To receive (受ける)",
"Rinasia": "Born (孵化/生まれる)",
"Rindou": "Caress (撫でる)",
"Ritto": "Airborne (放つ)",
"Roof": "Hole (穴)",
"Roofialaita": "Tunnel (トンネル)",
"Rook": "Bid farewell (別れる)",
"Rowt": "Abyss (奈落)",
"Rustie": "Reflect (映る)",
"Sai": "Morning (朝)",
"Salah": "Shadow (影)",
"Salie Proula": "Reverend Monsignor (司祭さま)",
"Samb": "At ease (済む)",
"San": "Touch (触れる)",
"Sanctue": "Sanctuary (聖城)",
"Sar": "Same (同じ)",
"Sartain": "Dawn (暁)",
"Saray": "Friend (友達)",
"Sarp": "Soup (スープ)",
"Saryate": "Together (一緒に)",
"Sar": "Together (一緒に)",
"ifa": "Together (一緒に)",
"Saus": "Millenium (千年)",
"Saut": "Voice (声)",
"Scape": "Paintbrush (絵の具)",
"Scteus": "Guardian (護り)",
"Sctution": "Protect (守る/護る)",
"Seeda": "To guide (導く)",
"Seek": "Say (云う)",
"Seeka": "To flow (流す) / To reflect (映す)",
"Seekle": "Faint (仄か)",
"Seema": "To realize/notice (気付く)",
"Seiren": "Sing (唄う)",
"Seiti": "Meaning (意味)",
"Sel": "True (本当)",
"Selaf": "True (本当)",
"Selanya": "Wander (彷徨う)",
"Selate": "Evening (宵)",
"Selvell": "Honest Feelings (本音)",
"Selep": "Skirt (スカート)",
"Senju": "Send (送る)",
"Shalm": "Being hurt (切ない)",
"Sharla": "Tree (樹)",
"Shay": "Fire (炎)",
"She": "Holy (神聖)",
"Shelim": "Silent (静か)",
"Shellarm": "Holy Temple (神殿)",
"Shellius": "God (神様)",
"Shiita": "A finish (結局)",
"Siala": "Song (唄)",
"Sigik": "To turn away (逸らす)",
"Sikid": "Consciousness (意識)",
"Siifii": "Saliva (唾液)",
"Siig": "To decide (決める)",
"Sindip": "Hyena (ハイエナ)",
"Sinis": "Left (左)",
"Sipil": "To slip (すり抜ける)",
"Siviliem": "Instinct (本能)",
"Sjylupe": "Thwart (挫ける)",
"Sjeld": "Rust (錆びる)",
"Skaid": "Look at sky",
"Skeem": "Start (始める)",
"Skelat": "Mock (あざ笑う)",
"Skie": "To cross (越える)",
"Skima": "Go under (潜る)",
"Skyar": "To follow (做う)",
"Slay": "Road/Journey (道/旅)",
"Sleetia": "Corridor (回廊)",
"Slialius": "To drain away (抜き取る)",
"Sloa": "Honey (蜂蜜)",
"Sol": "Smile (微笑)",
"Sole": "Soul (魂)",
"Solfe": "Unwind (ほどける)",
"Solien": "Sofa (ソファ)",
"Solte": "Behind (裏)",
"Sou": "Snow (雪)",
"Spai": "Welter (溺れる)",
"Spay": "Mirror (鏡)",
"Speixem": "Specimens (標本)",
"Sphiep": "Sphere (球)",
"Squa": "Face (顔)",
"Stache": "Drawer (ドロワー)",
"Staple": "Staircase (階段)",
"Staps": "To clap (叩く)",
"Stea": "Draw/Guide (描く/運ぶ)",
"Stegraid": "Revolving Lantern (走馬灯)",
"Stei": "View (景色)",
"Stica": "Hold (breath) (止める)",
"Stjpile": "to wipe (拭う)",
"Stodd": "Seat (席)",
"Story": "Story (物語)",
"Sween": "Sleep (眠る)",
"Swiina": "Wrapped (包む/纏う)",
"Swinia": "Shell (殻)",
"Swormin": "Take off (飛び込む)",
"Sworntie": "Put to sleep (眠らせる)",
"Sy": "Angel (天使)",
"Syeilla": "Angel (天使)",
"Syarfi": "Dress (ドレス)",
"Syena": "Apotheosis (神化)",
"Synapse": "Synapse (シナプス)",
"Talis": "Very beginning (最初/昔) / A long time (長い間)",
"Tarn": "Year (年)",
"Taz": "Time (時/頃)",
"Tozlom": "Time (時/頃)",
"Teejt": "Trap (閉じ込む)",
"Tehomea": "Depths/Abyss (深淵)",
"Tella": "Flow (流される)",
"Telly": "To leave (something for someone) (預ける)",
"Termz": "Clock (時計)",
"Theegie": "Rage (怒り)",
"Theek": "Knife (ナイフ)",
"Thloo": "Oh my God (大変)",
"Thuivili": "Busily (忙しい)",
"Tiag": "Scream (叫ぶ)",
"Ticcarm": "Little by little (少しずつ)",
"Ticcla": "Glass (ガラス)",
"Tigalm": "Destroy (潰す)",
"Tiika": "to disturb (かき乱す)",
"Tim": "Lamp (灯)",
"Tikk": "Blood (血)",
"Tit": "Poem (詩)",
"Tittri": "Retina (瞳)",
"Tleiket": "To organize (整理する)",
"Tlli": "Press (押す)",
"Tollm": "Spill out (零れだす)",
"Tollti": "drip (滴る)",
"Tone": "Monster (怪獣) / Rear (背)",
"Torch": "Traffic Lights (信号機)",
"Toriesta": "Witch (魔女)",
"Torjest": "Kill (殺す)",
"Torke": "To worship (礼拝)",
"Toubi": "To Open (eyes) (開ける)",
"Toup": "Type (種類)",
"Toys": "Toys (おもちゃ)",
"Traluki": "To be buried (埋もれる)",
"Trane": "Tear (泪/涙)",
"Tri": "Three (三)",
"Trico": "Too much (あんまり)",
"Tuklt": "Data (データ)",
"Tvulei": "Appearance (姿)",
"Ullem": "Depths (奥)",
"Unharla": "Chance (チャンス)",
"Vakka": "To possess (取り憑く)",
"Vaice": "Witness (証人)",
"Vala": "Wall (壁)",
"Veida": "Rolled number/ordinal number (目)",
"Veilatoriet": "Doll (人形)",
"Veit": "Red (赤い)",
"Velidi": "Cage (檻)",
"Vellediola": "Graveyard (墓場)",
"Velsiam": "Dirty (汚い)",
"Venesene": "Cluster (幽)",
"Verde": "Distorted (歪曲)",
"Verse": "Disappear (消え去る/消える)",
"Sadiet": "Disappear (消え去る/消える)",
"Rata": "Disappear (消え去る/消える)",
"Verry": "Word (言葉)",
"Via": "Journey (旅)",
"Viccla": "Glass (ガラス)",
"Vidd": "Queen (女王)",
"Viditt": "To preach (説く)",
"Vielakaite": "Lake (湖)",
"Viin": "to Search (探す)",
"Viizy": "Bug (gaming term) (バグ)",
"Vijg": "To be hungry for (飢える)",
"Vilkt": "Corpse (骸)",
"Vindi": "Bruise (痣)",
"Vinelo": "Winter (冬)",
"Visini": "Devil (悪魔)",
"Vins": "Evil (悪)",
"Visc": "To know (知る)",
"Vitui": "Great (formal) (よろしい)",
"Vivi": "Born (燈る)",
"Vleisa": "Distance (彼方)",
"Volp": "Ghosts (お化け)",
"Waltisala": "Hymn (讃美歌)",
"Way": "Answer (答え)",
"Ween": "very (end) (果て)",
"Wedikarti": "To save (救う)",
"Weilla": "Rose (薔薇)",
"Weika": "Secret (秘密)",
"Weliim": "Melt (溶ける)",
"Wely": "Sink (沈む)",
"Wend": "To swim (泳ぐ)",
"Wendiak": "Giant (巨大)",
"Wendiq": "To wear (around head area) (被る)",
"Whiil": "White (白)",
"Wiina": "Sleep (眠り)",
"Will": "Heartbeat (鼓動)",
"Wipt": "To throw (投げる)",
"Wipsam": "Line of Sight (視線)",
"Wiziliq": "Antimony (アンチノミー)",
"Wizlad": "to play (an act/perform) (演じる)",
"Woli": "To bless (授かる)",
"Wolme": "Carpet (絨毯)",
"Womphil": "Swallow (飲み込む)",
"Wond": "Wound (傷)",
"Wondist": "Wound (傷)",
"Wondidda": "Pain (痛い)",
"Xianya": "Think (思う)",
"Xlleidie": "Ghost (幽霊)",
"Yien": "Pull (引っ張る)",
"Yiep": "Please",
"Phier": "Please (お願い)",
"Yiela": "Give me (賜う)",
"Yulleia": "Gradually (ゆっくり)",
"Yutul": "A day (一日)",
"Yutulsinv": "Everyday (毎日)",
"Yuwlpie": "Utopia (ユートピア)",
"Zeit": "Moment (時間)",
"Zenoth": "Sigh (溜め息)",
"Zia": "Me (僕)",
"Zihilial": "Rich Color (極彩色)",
"Zill": "We (僕ら)",
"Zillyte": "We (僕ら)",
"Ziksii": "Well-mannered (お行儀いい)",
"Ziok": "Thunder (雷)",
"Ziokla": "Ptarmigan (雷鳥)",
"Zote": "Season (季節)",
"A": "1. And (if connecting two nouns together) 2. Interjectory phrase (at the beginning)/Imperative command",
"Ah": "1. And (if connecting two nouns together) 2. Interjectory phrase (at the beginning)/Imperative command",
"a": "1. And (if connecting two nouns together) 2. Interjectory phrase (at the beginning)/Imperative command",
"a Geeg": "acts like 〜ている/続ける (Present participle conjugation)",
"Aim": "(acts like くらい)",
"Alan": "if (たら)",
"Am": "Finally (やっと)",
"Amabell": "Finally (ようやく)",
"Amblu": "acts like など",
"Arte": "(acts like 〜たり)",
"Bis": "1.Placed at the end of the sentence: Here (ここ) (Bisoli is also used) 2.Placed anywhere else: It’s/This (これ/この)",
"Bistie": "That kind of (こんな)",
"Blem": "Who (誰)",
"Dia": "Well then... (それでは)",
"Dou/Dikta": "(Humble Impreative) (んだ)",
"Edil": "Each (ずつ)",
"em": "like (end ol) but structured backwards.",
"end": "And (if connecting more than two nouns together OR connecting two or more adjectives or numbers OR That, as in Days that I cried, mission that I failed)",
"Endaqlt": "Because (から)",
"Eik": "Too much (過ぎる)",
"Elaisic": "If (なら)",
"Elaind": "(tone reducer) (たった -> だけ)",
"Elie": "acts like へ/まで",
"Endjulf": "Because of that (そうして)",
"Epie": "I’d rather (方がいい)",
"es": "And (そして, or te-form/masu-form to modify verb to create compound sentences)",
"far": "(quoting verb) that",
"Fevla": "Why not... (どうだい)",
"Fiem": "Counter for Sheets (枚)",
"Fiqq": "Careful (よく〜)",
"folme": "From (から)",
"forle": "Before (前に)",
"Hols": "(Expresses desire for something)",
"Ied": "Should (〜ば良い)",
"Ieq": "As a... (...として)",
"Iequim": "Entirely (まるで)",
"Ifa": "With (で)",
"Ignai": "Never, nothing (ないように/ことのない)",
"Iis": "(Japanese Causative Form)",
"Ijlim": "When (after a long time)(ころ)",
"il": "To (に)",
"ild": "To (に)",
"Ilek": "Somehow (どうにかして)",
"Iqyur": "(Honorific prefix used for postion higher than speaker) (さま)",
"iy": "(Sentence breaker, or topic marker)",
"Imeila": "Despite (ところで)",
"Imm": "acts like に/で",
"Karna": "Again (また)",
"Kueip": "-en (〜にする)",
"Koll": "Current State (まま)",
"Kulu": "Can (Japanese Potential Form)",
"Laiz": "acts like だろう",
"Lar": "(Attach next kanji as prefix) / Towards",
"Leidiq": "try to",
"len": "Intransitive modifier (落とす -> 落ちる)",
"Lef": "Like (みたい/よう)",
"Lend": "Are (Interrogative) (か)",
"Liaphi": "(Neutral Honorific) (さん)",
"lid": "acts like 真",
"-in": "acts like 真",
"Lili": "Just (だけ)",
"Lim": "Under (下)",
"Likti": "Just (ただ)",
"Lishe": "Let’s (Japanese volitional form)",
"Loosya": "Every/even (すら)",
"Lqll": "(Currently unknown, but possibly used to indicate relatives)",
"Mei": "The (relating to deity or high figure)",
"Mols": "only (だけ)",
"Nai": "Not a... (無い)",
"neu": "Nor (ない)",
"Noa": "Prefix of nothingness (-less) (無)(Note: some words have Noa appear as a suffix)",
"Note": "Thing (こと)",
"O": "Am, is, are, was, were, might be, etc. (Usually dropped)",
"ob": "(Past participle conjugation)",
"occia": "Even if (だって)",
"Ofa": "(Possessive counter, used to prevent frequent use of current pronoun)",
"ol": "was, were (Past modifier)",
"Ola": "From (inside) (から)",
"olfe": "acts like か(used for asking details with question word (i.e. 5W1H))",
"Oltia": "That kind of (そんな)",
"Olzy": "Must (なくちゃ)なくちゃ)",
"Ord": "by (something) / All (the way) (as in 全〜)",
"orilim": "(Unknown for now)",
"Osa": "will be/still (まだ)",
"ou": "Of the (acts like の (with person/people being the modified), but structured backwards)",
"Pileknoa": "No matter (どれだけ…も)",
"Plousa": "(Counter for occurrences) (度)",
"Poa": "(Counter for small animals) (匹)",
"Poet": "Please (don’t) (ないで)",
"Poetklar": "While (ながら)",
"Poetolt": "In the end / End result (結局)",
"Porsa": "to the full range, as much as (だけ)",
"Poutie": "when/if (と/なら)",
"Qleea": "acts like 〜てしまう (completely)",
"Imblu": "acts like 〜てしまう (completely)",
"qls": "Suffix to indicate plurality (たち)",
"Queit": "Even though (のに)",
"Roa": "Even though (のに)",
"Ra": "will be (future tense)",
"Rie": "Eventually (やがて)",
"Sar": "In Accordance to (-通り)",
"sii": "Anymore (もう…ない) / Later (直に)",
"sip": "(acts like のさ)",
"Shelta": "Surely (きっと)",
"Foul": "Surely (きっと)",
"Ticca": "A bit (少し)",
"Tiisa": "It seems...",
"tie": "Inside (when it’s topical) (には)",
"Tou": "Want (〜たい)",
"Nadi": "Want (〜たい)",
"tou": "Even with (Vた + って)",
"Twiik": "That other time (あの)",
"Veis": "Among (間)",
"Velaiye": "I plan to (つもり)",
"Vell": "1. No matter what (必ず) (Usually dropped in translation to indicate a condition that should be met) 2. Acts like も(ない)/ことのない 3. Likely to (だろう)",
"Wasiim": "Why (どうして)",
"weil": "Inside (で)",
"Well": "(Extent of time)(【こ・そ・あ】れほど)",
"Wilenq": "How (なんて〜)",
"Wimb": "However (ただし)",
"Xaide": "That (Archaic) (彼の)",
"Xia": "(depends on position) Before a noun: That (それ/その) Before a verb, context is about past: (Acts like 〜てしまう) Before a verb, context is about near future: To come… (〜てくる)",
"Xieti": "On that time (その時)",
"Yiele": "Not (ことのなかった)",
"Yien": "(Japanese passive conjugation)",
"Zel": "Anything (何も)",
"alia": "Quite a...",
"isiam": "(verb) Back (〜返す)",
"it": "(turns a verb to an adjective)",
"jima": "(Acts like 〜てきた)",
"lait": "To modify an adjective to adverb (-ly)",
"lea": "Verb to adjective",
"mea": "Verb to adjective",
"ll": "Seems (Vます + ～そう)",
"oli": "Attach to place when が/は is used. (indicates a place)",
"s": "Suffix used to pluralize (pro)noun (たち)",
"soil": "Suffix used to modify an activity to an object relating to it (-管)",
"t": "Gerund modifier (事/delete する) (does not apply to all verbs)",
"tea": "(Harsh emphasis)",
"mia": "To match with each other (～合う)",
"ne": "Suffix used to someone for an activity (被-)",
"yatt": "(to turn a verb into a noun without adding -ing, only works on certain verbs.",
"yur": "add honorific prefix to previous word (お〜)(If ends on a silent letter that will be omitted.)",
"Voi": "may be (かもしれない)"
};